spring.application.name=chat

# Configuração do Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.title=Chat System API
springdoc.swagger-ui.version=1.0.0
springdoc.swagger-ui.display-operation-id=true
springdoc.swagger-ui.show-common-extensions=true
springdoc.swagger-ui.try-it-out-enabled=true

# H2 em memória
spring.datasource.url=jdbc:h2:mem:localtestdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

# Driver e credenciais padrão
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

